import type { Metadata } from 'next';
import { Geist, Geist_Mono, Alegreya } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/contexts/AuthContext';
import { LangGraphProvider } from '@/contexts/LangGraphContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const alegreya = Alegreya({
  variable: '--font-alegreya',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} ${alegreya.variable}`}
    >
      <body>
        <AuthProvider>
          <LangGraphProvider>{children}</LangGraphProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
